---
- name: Install node and npm
  hosts: webserver
  become: true
  tasks:

    - name: Update apt repo and cache
      ansible.builtin.apt:
        update_cache: true
        force_apt_get: true
        cache_valid_time: 3600

    - name: Install nodejs and npm
      ansible.builtin.apt:
        pkg:
          - nodejs
          - npm

- name: Deploy nodejs app
  hosts: webserver
  become: true
  vars_files:
    - ../project-vars
  tasks:

    - name: Unpack the .tgz archive
      ansible.builtin.unarchive:
        src: "{{local_artifact_folder_location}}/node-ex-website-{{app_version}}.tgz"
        dest: /home/ubuntu

    - name: Install dependencies
      community.general.npm:
        path: /home/ubuntu/package

    - name: Run webserver
      ansible.builtin.command:
        chdir: /home/ubuntu/package
        cmd: npm start
      async: 1000
      poll: 0

    - name: Ensure app is running
      ansible.builtin.shell:
        cmd: ps aux | grep node
      register: app_status
    - ansible.builtin.debug:
        msg: "{{app_status.stdout_lines}}"
